USE tienda;

SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS "Price in €", ROUND(precio * 1.10, 2) AS "Price in $" FROM producto;
SELECT nombre AS "nom de producto", precio AS "euros", ROUND(precio * 1.10, 2) AS "dòlars" FROM producto;
SELECT UPPER(nombre) AS "UpperCase Name" FROM producto;
SELECT LOWER(nombre) AS "LowerCase Name", precio FROM producto;
SELECT nombre, CONCAT(UPPER(SUBSTRING(nombre, 1, 2)), LOWER(SUBSTRING(nombre, 3, LENGTH(nombre)))) AS "Two first letters to UpperCase" FROM fabricante;
SELECT nombre, ROUND(precio, 0) AS "Rounded price" FROM producto;
SELECT nombre, TRUNCATE(precio, 0) AS "Truncate price" FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3, 2;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.nombre;
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre;
SELECT producto.codigo AS "Product code", producto.nombre AS "Product name", precio, fabricante.codigo AS "Manufacturer code", fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio ASC LIMIT 1;
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio DESC LIMIT 1;
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo';
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Crucial' AND producto.precio > 200;
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Asus' OR fabricante.nombre = 'Hewlett-Packard' OR fabricante.nombre = 'Seagate';
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE RIGHT(fabricante.nombre, 1) = 'e';
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE '%w%';
SELECT producto.nombre AS "Product name", precio, fabricante.nombre AS "Manufacturer name" FROM producto INNER JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE producto.precio >= 180 ORDER BY producto.precio ASC, producto.nombre;
SELECT fabricante.codigo, fabricante.nombre FROM fabricante JOIN producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre AS "Manufacturer name", producto.nombre AS "Product name" FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre;
SELECT fabricante.nombre  FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante = fabricante.codigo WHERE producto.codigo_fabricante IS NULL;
SELECT fabricante.nombre AS "Manufacturer name", producto.nombre AS "Product name" FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo";
SELECT producto.*, fabricante.nombre AS "Manufacturer name" FROM producto LEFT JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE precio = (SELECT MAX(precio) FROM producto LEFT JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo");
SELECT producto.nombre AS "Product name", fabricante.nombre AS "Manufacturer name" FROM  producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo" ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre AS "Product name", fabricante.nombre AS "Manufacturer name" FROM  producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Hewlett-Packard" ORDER BY precio LIMIT 1;
SELECT producto.*, fabricante.nombre AS "Manufacturer name" FROM  producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE precio >= (SELECT MAX(precio) FROM producto LEFT JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo");
SELECT producto.*, fabricante.nombre AS "Manufacturer name" FROM  producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Asus" AND precio > (SELECT AVG(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE fabricante.nombre = "Asus"));